// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"go-nunu/internal/repository"
	"go-nunu/internal/server"
	"go-nunu/pkg/app"
	"go-nunu/pkg/casbin"
	"go-nunu/pkg/log"
)

// Injectors from wire.go:

func NewWire(viperViper *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	db := repository.NewDB(viperViper, logger)
	cachedEnforcer := casbinPkg.NewEnforcer(db)
	migrateServer := server.NewMigrateServer(db, logger, cachedEnforcer)
	appApp := newApp(migrateServer)
	return appApp, func() {
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewUserRepository, repository.NewRoleRepository, repository.NewPermissionRepository)

var serverSet = wire.NewSet(server.NewMigrateServer)

// build App
func newApp(
	migrateServer *server.MigrateServer,
) *app.App {
	return app.NewApp(app.WithServer(migrateServer), app.WithName("demo-migrate"))
}

// 添加 Casbin 提供者
var casbinSet = wire.NewSet(casbinPkg.NewEnforcer)
