// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/google/wire"
	"github.com/spf13/viper"
	"go-nunu/internal/handler"
	"go-nunu/internal/job"
	"go-nunu/internal/repository"
	"go-nunu/internal/router"
	"go-nunu/internal/server"
	"go-nunu/internal/service"
	"go-nunu/pkg/app"
	"go-nunu/pkg/aws"
	"go-nunu/pkg/jwt"
	"go-nunu/pkg/log"
	"go-nunu/pkg/server/http"
	"go-nunu/pkg/sid"
)

// Injectors from wire.go:

func NewWire(cfg *viper.Viper, logger *log.Logger) (*app.App, func(), error) {
	jwtJWT := jwt.NewJwt(cfg)
	handlerHandler := handler.NewHandler(logger)
	db := repository.NewDB(cfg, logger)
	repositoryRepository := repository.NewRepository(logger, db)
	transaction := repository.NewTransaction(repositoryRepository)
	sidSid := sid.NewSid()
	serviceService := service.NewService(transaction, logger, sidSid, jwtJWT)
	userRepository := repository.NewUserRepository(repositoryRepository)
	userService := service.NewUserService(serviceService, userRepository)
	userHandler := handler.NewUserHandler(handlerHandler, userService)
	cloudflareR2, cleanup, err := aws.NewR2Client(cfg)
	if err != nil {
		return nil, nil, err
	}
	commonService := service.NewCommonService(cloudflareR2)
	commonHandler := handler.NewCommonHandler(handlerHandler, commonService, cloudflareR2)
	roleRepository := repository.NewRoleRepository(repositoryRepository)
	roleService := service.NewRoleService(serviceService, roleRepository)
	roleHandler := handler.NewRoleHandler(handlerHandler, roleService)
	permissionRepository := repository.NewPermissionRepository(repositoryRepository)
	permissionService := service.NewPermissionService(serviceService, permissionRepository)
	permissionHandler := handler.NewPermissionHandler(handlerHandler, permissionService)
	routerDeps := router.RouterDeps{
		Logger:            logger,
		Config:            cfg,
		JWT:               jwtJWT,
		UserHandler:       userHandler,
		CommonHandler:     commonHandler,
		RoleHandler:       roleHandler,
		PermissionHandler: permissionHandler,
	}
	httpServer := server.NewHTTPServer(routerDeps)
	jobJob := job.NewJob(transaction, logger, sidSid)
	userJob := job.NewUserJob(jobJob, userRepository)
	jobServer := server.NewJobServer(logger, userJob)
	appApp := newApp(httpServer, jobServer)
	return appApp, func() {
		cleanup()
	}, nil
}

// wire.go:

var repositorySet = wire.NewSet(repository.NewDB, repository.NewRepository, repository.NewTransaction, repository.NewUserRepository, repository.NewRoleRepository, repository.NewPermissionRepository)

var serviceSet = wire.NewSet(service.NewService, service.NewUserService, service.NewRoleService, service.NewPermissionService, service.NewCommonService)

var handlerSet = wire.NewSet(handler.NewHandler, handler.NewUserHandler, handler.NewRoleHandler, handler.NewPermissionHandler, handler.NewCommonHandler)

var jobSet = wire.NewSet(job.NewJob, job.NewUserJob)

var serverSet = wire.NewSet(server.NewHTTPServer, server.NewJobServer)

// build App
func newApp(
	httpServer *http.Server,
	jobServer *server.JobServer,

) *app.App {
	return app.NewApp(app.WithServer(httpServer, jobServer), app.WithName("demo-server"))
}

// 声明 R2 构造函数
var awsSet = wire.NewSet(aws.NewR2Client)
